import json
import re
import time
from typing import Any

from langchain_core.prompts import ChatPromptTemplate

from src.observability.tracing import get_langfuse_callbacks, trace_generation

from src.models import ContextualizationOutput, ContractChangeOutput
from src.providers.llm_factory import get_chat_model

EXTRACTION_SYSTEM_PROMPT = """
You are ExtractionAgent, a specialized legal contract change extraction agent.

Your role is to identify concrete differences between an original contract and an amendment.

You receive:
1. The parsed text of the original contract.
2. The parsed text of the amendment.
3. A structural contextual map generated by ContextualizationAgent.

Your task:
- Identify additions.
- Identify deletions.
- Identify modifications.
- Identify affected sections.
- Identify legal or commercial topics touched.
- Produce an executive summary of the changes.

Important distinction:
- The contextual map is guidance.
- The final extraction must be based on the actual original and amendment texts.
- Do not invent changes that are not supported by the provided documents.
- Do not provide legal advice.
- Do not evaluate enforceability.
- Do not recommend actions.
- Return valid JSON only.
- Do not wrap the JSON in markdown.

Classification rules:
- Use "addition" when content exists in the amendment but not in the original contract.
- Use "deletion" when content exists in the original contract but is removed or not represented in the amendment.
- Use "modification" when a section exists in both documents but the text, amount, term, period, scope, obligation or condition changed.
- Use "unclear" only when the documents do not provide enough evidence.

Output rules:
- Items inside additions must have change_type = "addition".
- Items inside deletions must have change_type = "deletion".
- Items inside modifications must have change_type = "modification".
- Use null for original_text when the change is an addition.
- Use null for amendment_text when the change is a deletion.
- sections_changed should contain concise section ids or titles.
- topics_touched should contain concise legal/commercial topics.
"""

EXTRACTION_USER_PROMPT = """
Case ID:
{case_id}

Expected JSON schema:
{json_schema}

Original contract parsed text:
{original_contract_text}

Amendment parsed text:
{amendment_text}

Contextual map:
{contextualization_json}

Return only valid JSON that matches the schema.
"""

class ExtractionAgentError(RuntimeError):
    """Raised when the extraction agent fails."""

def _extract_response_text(response: Any) -> str:
    content = getattr(response, "content", response)

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        parts :list[str] = []

        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict) and "text" in item:
                parts.append(str(item["text"]))
            else:
                parts.append(str(item))

        return "\n".join(parts)

    return str(content)

def _extract_json_object(raw_text: str) -> dict[str, Any]:
    cleaned = raw_text.strip()

    if cleaned.startswith("```"):
        cleaned = re.sub(
            r"^```(?:json)?",
            "",
            cleaned,
            flags=re.IGNORECASE,
        ).strip()
        cleaned = re.sub(r"```$", "", cleaned).strip()

    start = cleaned.find("{")
    end = cleaned.rfind("}")

    if start == -1 or end == -1 or end <= start:
        raise ExtractionAgentError(
            "The model response did not contain a valid JSON object."
        )

    json_text = cleaned[start: end + 1]

    try:
        return json.loads(json_text)
    except json.JSONDecodeError as error:
        raise ExtractionAgentError(
            f"Failed to parse extraction JSON: {error}"
        ) from error

def _serialize_contextualization(
        contextualization: ContextualizationOutput | dict[str, Any],
) -> str:
    if isinstance(contextualization, ContextualizationOutput):
        return contextualization.model_dump_json(indent=2)

    return json.dumps(
        contextualization,
        indent=2,
        ensure_ascii=False
    )

def run_extraction_agent(
        case_id: str,
        original_contract_text: str,
        amendment_text: str,
        contextualization: ContextualizationOutput | dict[str,Any],
        provider: str | None = None
) -> ContractChangeOutput:
    started_at = time.perf_counter()

    llm = get_chat_model(
        provider=provider,
        temperature=0,
    )

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", EXTRACTION_SYSTEM_PROMPT),
            ("user", EXTRACTION_USER_PROMPT),
        ]
    )

    json_schema = json.dumps(
        ContractChangeOutput.model_json_schema(),
        indent=2,
        ensure_ascii=False,
    )

    contextualization_json = _serialize_contextualization(contextualization)

    messages = prompt.format_messages(
        case_id = case_id,
        json_schema= json_schema,
        original_contract_text=original_contract_text,
        amendment_text=amendment_text,
        contextualization_json=contextualization_json,
    )

    callbacks = get_langfuse_callbacks()

    llm_config: dict[str, Any] = {
        "run_name": "extraction_llm",
        "tags": ["legalmove", "extraction-agent"],
        "metadata": {
            "case_id": case_id,
            "agent": "ExtractionAgent",
        },
    }

    if callbacks:
        llm_config["callbacks"] = callbacks

    with trace_generation(
        name="extraction_agent_generation",
        model=getattr(llm, "model_name", "unknown"),
        input_data={
            "case_id": case_id,
            "original_contract_length": len(original_contract_text),
            "amendment_length": len(amendment_text),
        },
        metadata={
            "agent": "ExtractionAgent",
            "provider": provider or "default",
        },
    ) as generation:
        response = llm.invoke(messages, config=llm_config)
        response_text = _extract_response_text(response)

        generation.update(
            output_data={
                "response_preview": response_text[:2000],
            }
        )

        
    response_data = _extract_json_object(response_text)

    response_data["case_id"] = response_data.get("case_id", case_id)

    try:
        extraction_output = ContractChangeOutput.model_validate(
            response_data
        )
    except Exception as error:
        raise ExtractionAgentError(
            f"Extraction output validation failed: {error}"
        ) from error

    latency_seconds = round(time.perf_counter() - started_at,3)

    extraction_output = extraction_output.model_copy(
        update={
            "latency_seconds": latency_seconds
        }
    )

    return extraction_output